version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-jessie

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Build and install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: 
          name: Run tests with JUnit as reporter
          command: ./node_modules/.bin/jest --collect-coverage --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-results
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results

