on: pull_request
name: Auto Label Pull Request
jobs:
  pRLabelByFiles:
    name: PR label by Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PR label by Files
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
